### ISSUE TITLE
How to get the access_token instead of id_token

### ISSUE THREAD

**Issue by binobose** [survirtual/vue-adal#15] opened 2018-08-14 14:00 UTC
Currently I am getting the id_token in the querystring as response if I am redirecting to a URL. How can I change it to access_token. Please advise.

**Comment by survirtual** [comment] 2018-10-01 21:00
You use the ID token to get an Access Token, as seen in #2 and the examples.

**Comment by survirtual** [comment] 2018-10-01 21:00
Duplicate of #2

**Closed by survirtual** 2018-10-01 21:00 UTC
